### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by paladox** [comment]
I am not sure how to fix these errors. Could someone fix them please.

**Comment by paladox** [comment]
It causes other repos that depend on this repo to fail.

**Comment by houli** [comment]
More problems with the removed path.exists function in node 0.12 as you can see on these lines https://github.com/fjakobs/async.js/blob/master/test/fs.test.js#L37
https://github.com/fjakobs/async.js/blob/master/test/fs.test.js#L48
https://github.com/fjakobs/async.js/blob/master/test/fs.test.js#L60
https://github.com/fjakobs/async.js/blob/master/test/fs.test.js#L133
https://github.com/fjakobs/async.js/blob/master/test/fs.test.js#L140

**Comment by paladox** [comment]
Could I have help to fix errors please. I am not sure what to change that code to.

**Comment by houli** [comment]
The problem is not with the parts you changed in the calls to `Path.exists`. The problem is calling `Path.exists`. This function was marked deprecated because the exists function was moved from the path module to the fs module. In node 0.12 the deprecated function was removed.
One way to make sure this works in old and new versions of node is shown here https://github.com/fjakobs/async.js/blob/master/lib/plugins/fs-node.js#L12
All the places where `Path.exists` should have been updated when this code was written but clearly the code in the tests wasn't.

**Comment by houli** [comment]
I've created a pull request here to fix these tests not passing and to also run CI tests against the latest four versions of node. https://github.com/fjakobs/async.js/pull/27

**Comment by paladox** [comment]
Thanks.

**Comment by fjakobs** [comment]
this this PR still needed?

**Comment by paladox** [comment]
https://github.com/fjakobs/async.js/pull/28

**Pull request closed without merging**
